### PR TITLE
Add Support For Alpha PNGs

### PR DESCRIPTION
**Pull request by matt-attack**
This adds an overridable per stream-type decode function for handling other image formats such as those containing alpha.

### CODE REVIEW

**Comment by matt-attack** [comment]
Bump?

**Comment by bjsowa** [comment]
Could you rebase your commit or merge changes from ros1 branch so that the workflow triggers?

**Comment by matt-attack** [comment]
Pulled in ros1 but seems the CI needs approval to run or something.

**Review by bjsowa — APPROVED** [review]
Tried it and it seems to work.

**Pull request merged**
