### PR TITLE
Add compressedImage

### PR DESCRIPTION
**Pull request by ahcorde**
Hi,

I would like to add a callback to compressedImage, The main idea is to avoid decompress and compress the image every time. I only want to move the image data without processing the image (cv::imencode(...)). But I have some problems when I try to call the callback, The callback is never called. In the following line you can see how I bind the method. https://github.com/erlerobot/web_video_server/blob/develop/src/image_streamer.cpp#L21.

Any ideas are most welcome

### CODE REVIEW

**Comment by mitchellwills** [comment]
At first glance it looks correct. Are you sure the compressed topic is being published (is compressed_image_transport installed?). Also if you are running web_video_server and the image publisher on the same machine you may just want to run them in nodelets under the same nodelet manager. That way there is not extra decompress/compress and a zero copy of the image.

I know that right now web_video_server does not have a nodelet version, but it should be pretty easy to implement.

**Comment by jihoonl** [comment]
This is +1 feature for me as well. And nodelet does not fit for my usecase. web_video_server is hosted in wired computer while robot is sending compressed image via wireless.

**Comment by mitchellwills** [comment]
Hmm, I can look into this more at some point unless your interested in implementing it. I probably won't get to it for at least a couple weeks.

**Comment by mitchellwills** [comment]
Hey so I took a stab at this the past couple days and came up with something.
You can check it out here: https://github.com/mitchellwills/web_video_server/tree/compressed
NOTE: you will need to also need the latest version of async_web_server_cpp from here https://github.com/mitchellwills/async_web_server_cpp/tree/develop

I took the approach to specify a new stream type (ros_compressed) instead of trying to modify the mjpeg type. This is to remove ambiguity when additional options are specified. (For example if you specify a size should it decode and reencode the frame, also if png compression is used in ROS should the png be reencoded to a jpeg?) By simply implementing it as a separate type this isn't an issue. I also built it so that you can stream png images, just like jpeg images in mjpegs. (Apparently browsers support this...)

**Comment by mitchellwills** [comment]
Does this sound like a solution that works for you guys?

**Comment by jihoonl** [comment]
Looks good! Would it be compatible with mjpeg canvas?

**Comment by rctoris** [comment]
`mjpegcanvasjs` simply puts the URL in the `src` of a hidden HTML image component, lets the browser natively decode it, and then read the RGB values directly. So, in theory, if the browser can decode it, mjpegcanvas should display it.

**Comment by mitchellwills** [comment]
Made a pull request #16

**Comment by mitchellwills** [comment]
Is this closeable now that #16 is merged?

**Comment by ahcorde** [comment]
Yes, I think so

**Pull request closed without merging**
