### PR TITLE
Adds support for streaming ROS compressed image topics without the need to reencode them

### PR DESCRIPTION
**Pull request by mitchellwills**
This also adds support for an updated API in async_web_server_cpp and requires WPI-RAIL/async_web_server_cpp#5

### CODE REVIEW

**Comment by jihoonl** [comment]
Travis failed

**Comment by mitchellwills** [comment]
Yes this requires WPI-RAIL/async_web_server_cpp#5

**Comment by jihoonl** [comment]
Ahha Ok. I didn't notice. :neckbeard:

**Comment by mitchellwills** [comment]
It will fail until that PR is released as this travis build pulls from the release repo. I could switch it to the shadow repo so the build will pass without waiting for a sync

**Comment by rctoris** [comment]
Re-triggering after merge

**Comment by rctoris** [comment]
@mitchellwills can you modify the travis file to build async_web_server_cpp from source until its released?

**Comment by mitchellwills** [comment]
Should  push another commit that moves travis to use the shadow repo (requiring async_web_server_cpp to be released, which will cause web_video_server to fail on the build farm until this is released) or should I switch to checking out async_web_server_cpp from source on travis.

**Comment by mitchellwills** [comment]
Building now

**Comment by rctoris** [comment]
:+1:

**Pull request merged**
