### PR TITLE
Develop minimum rate stream

### LINKED ISSUE #7: vp8 encoding is flakey in browsers and in vlc
Using the develop branch: We saw that after a time, the vp8 streams in a browser slowed down after 5-10 seconds to about 1 frame every few seconds. Playing the same stream with vlc version 2.1.4 gives these outputs during such slowdown:

[0x7f9ce80009b8] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1000 ms)
[0x7f9ce80009b8] main input error: ES_OUT_RESET_PCR called
[vp8 @ 0x7f9cd8c3fea0] Discarding interframe without a prior keyframe!
[vp8 @ 0x7f9cd8c40300] Discarding interframe without a prior keyframe!
[vp8 @ 0x7f9cd8c42c40] Discarding interframe without a prior keyframe!
[vp8 @ 0x7f9cd8c455a0] Discarding interframe without a prior keyframe!
[vp8 @ 0x7f9cd8c3fea0] Discarding interframe without a prior keyframe!
[vp8 @ 0x7f9cd8c40300] Discarding interframe without a prior keyframe!

vlc eventually recovers and the stream becomes fluent again, but our Chrome browser does not.

http://superuser.com/questions/589796/how-to-remove-interframe-errors-from-webm

This issue doesn't crop up when streaming as an mjpeg, although vlc gives in that case:
"[mjpeg @ 0x7f0168c277e0] No JPEG data found in image" a zillion times...

### PR DESCRIPTION
**Pull request by psoetens**
This is a series of patches to fix #7 but to also support streaming images of nodes that only publish an image once in a while. If nodes don't republish an image, the web_video_server and/or browser get lost and no longer update the video element in the browser.

Finally, it was necessary to modify some of the encoding parameters in order to get a clean video stream at the browser. Some lag seems to be added, it's not clear if this could be improved again.

### CODE REVIEW

**Comment by rctoris** [comment]
@mitchellwills can you take a look at this when you get a chance?

**Comment by mitchellwills** [comment]
While this performs fine when the browser is running on the same machine as the server it runs significantly slower when streaming over wifi (less than 50%). I think this has to do with the modified time_base.den

**Comment by psoetens** [comment]
We only tested this over LAN streaming from a fanless/embedded core i7 CPU.  With slower, are you pointing at lag, or dropped frames? The main issue was that the stream just got choppy within 5-10 seconds anyway in any browser, so what are you comparing then ?

**Comment by mitchellwills** [comment]
I'm not sure if it was dropping frames, but the video was playing back at a rate slower than real time. This caused the video to lag further and further behind as time progressed (not a fixed lag). I do not see any lag, choppy video, etc, when streaming on the same machine. (NOTE these were for the mjpeg streaming)

When using vp8 I see it freeze every few seconds and then catch up when streaming locally. I see similar results when streaming over wifi, but with a little more lag (but the lag time seems to be fixed).

**Comment by rctoris** [comment]
Merge failure due to out-of-date code. Please re-open with up-to-date code if still valid.

**Pull request closed without merging**
