### PR TITLE
Add ros_environment to test dependencies

### PR DESCRIPTION
**Pull request by bjsowa**
Attempt to fix failing dev jobs on ROS buildfarm

### CODE REVIEW

**Comment by bjsowa** [comment]
I would like to set up webhooks to trigger PR jobs in the ROS buildfarm. Unfortunately, I got "demoted" from admin to moderator of this repository and am unable to do this. @amacneil @MatthijsBurgh any help?

**Comment by MatthijsBurgh** [comment]
@bjsowa your permissions should be fixed now.

**Comment by bjsowa** [comment]
@ros-pull-request-builder retest this please

**Comment by bjsowa** [comment]
This seems to have fixed the build on ROS buildfarm.
Iron: [Build Status](https://build.ros2.org/job/Ipr__web_video_server__ubuntu_jammy_amd64/)
Jazzy: [Build Status](https://build.ros2.org/job/Jpr__web_video_server__ubuntu_noble_amd64/)
Rolling: [Build Status](https://build.ros2.org/job/Rpr__web_video_server__ubuntu_noble_amd64/)

**Review by sea-bass — APPROVED** [review]

**Pull request merged**
